#!/bin/sh
HISTFILE="${XDG_CACHE_HOME}/zsh/history"
HISTSIZE=100000
SAVEHIST=100000

export CLICOLOR=1 
export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd
export LS_COLORS='no=00;37:fi=00:di=00;33:ln=04;36:pi=40;33:so=01;35:bd=40;33;01:'

eval "$(starship init zsh)"
