[cmd_duration]
format = "[祥$duration]($style) "

[directory]
read_only = " "

[directory.substitutions]
# "/mnt/c/Users/Brian/Desktop/projects" = "projects"

[jobs]
symbol = "華"

[memory_usage]
symbol = "神 "

[package]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "
