set hidden
set noswapfile
set backupcopy=yes
set number
set nowrap
set scrolloff=8
set laststatus=2
set noshowmode
set updatetime=50
set colorcolumn=80
set signcolumn=yes
set wildmenu
set encoding=utf8

" Searching
set incsearch
set nohlsearch

" Tabs and Indentations
set tabstop=8
set softtabstop=4
set shiftwidth=4
set expandtab

syntax enable
filetype plugin indent on
set background=dark
colorscheme hybrid
let g:lightline = {
\   'colorscheme': 'Tomorrow_Night',
\}

let mapleader = " "

" NERDTree
autocmd BufEnter * if tabpagenr('$') == 1
    \ && winnr('$') == 1
    \ && exists('b:NERDTree')
    \ && b:NERDTree.isTabTree()
    \ | quit | endif
autocmd BufWinEnter * silent NERDTreeMirror
let NERDTreeDirArrowExpandable = "\u00a0"
let NERDTreeDirArrowCollapsible = "\u00a0"
nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>

" ALE
let g:ale_linters = {
\   'javascript': ['eslint'],
\}
let g:ale_fixers = {
\   '*': ['remove_trailing_lines', 'trim_whitespace'],
\   'javascript': ['prettier', 'eslint'],
\}
let g:ale_fix_on_save = 1
let g:ale_linters_explicit = 1

packloadall
silent! helptags ALL
