#!/bin/zsh

# Function to source files if they exist
function zsh_add_file() {
    	[ -f "$ZDOTDIR/$1" ] && source "$ZDOTDIR/$1"
}

function zsh_add_plugin() {
	dir="/usr/share/zsh/plugins"
	([ -f "$dir/$1/$1.zsh" ] && source "$dir/$1/$1.zsh") || /
	[ -f "$dir/$1/$1.plugin.zsh" ] && source "$dir/$1/$1.zsh"
}
